### ISSUE TITLE
stackOffsetX and stackOffsetY don't work on iOS but they do on Android

### ISSUE THREAD

**Issue by mariovillamizar** [swaplet/react-native-swipe-cards-deck#12] opened 2021-04-09 17:16 UTC
If I swipe the cards on iOS I can see the stack under the main card though.
Thanks for this nice library!

**Comment by eyalabs** [comment] 2021-05-02 06:31
I'll check this out

**Comment by eyalabs** [comment] 2021-05-22 16:05
It seems to me that the problem is bigger than the offset.. on iOS I get a stack of cards hiding each other (yet this is not how it is meant to be - check android for instance).
I'll see what I can do

**Comment by eyalabs** [comment] 2021-05-22 16:24
Sorry for the late fix, but it is now fixed along with the prev. comment... you can get it at the latest ver 0.2.20

**Closed by eyalabs** 2021-05-22 16:24 UTC
Labels: bug
