### ISSUE TITLE
Stack render without fixed layout

### ISSUE THREAD

**Issue by JSDevelopment17** [swaplet/react-native-swipe-cards-deck#9] opened 2021-03-10 09:30 UTC
Hello.
I love this updated library! I am however having issues with the stack rendering. If I specify an absolute width and height it works, but if I'm using flex or specifying height/width as a % of the parent view the cards don't appear.
Is this a bug?
Thanks,
Steve.

**Comment by JSDevelopment17** [comment] 2021-03-10 17:33
Hello,
I'm using the following SwipeCards setup:
`<SwipeCards
cards={this.props.cards}
                                keyExtractor={(cardData) => String(cardData.product_id)}
                                stack={true}
                                stackDepth={3}
                                stackOffsetY={25}
                                renderCard={(cardData) => this.renderCard({...cardData})}
                                showYup={true}
                                showNope={true}
                                handleYup={this.handleYup.bind(this)}
                                handleNope={this.handleNope.bind(this)}
                                renderYup={(pan) => <BagView {...pan}/>}
                                renderNope={(pan) => <BinView {...pan}/>}
                                />`

with renderCard:
`renderCard(item) {
        return (
            <View style = {{flex: 1, backgroundColor: 'white'}}>
            </View>
        )
    }`

and the cards don't display. If I change renderCard to
`renderCard(item) {
        return (
            <View style = {{width: 300, height: 300}}>
            </View>
        )
    }`

I can see the cards. The container has a flex of 1 (confirmed to be displaying correctly). I'm new to mobile development and RN so might be missing something obvious!

**Comment by eyalabs** [comment] 2021-03-10 18:06
Can you attach the type and style of the parent component (holding the swipe cards)?

**Comment by JSDevelopment17** [comment] 2021-03-10 19:08
This is contained within a View component:
`<View style={{ flex: 1, padding: 0, }}>`

And this component is then contained within an Animated.View component.

**Comment by JSDevelopment17** [comment] 2021-03-11 08:52
I have tried stripping back all additional views on the page so that it only displays the cards, but still doesn't work with flex or layout specified as a % (e.g. `height: '100%`)

**Comment by eyalabs** [comment] 2021-03-11 10:00
We'll check this next week

**Comment by JSDevelopment17** [comment] 2021-03-11 17:20
Thanks so much for your support

**Comment by creativemind1** [comment] 2021-03-24 07:10
Thanks @eyalabs for your support and update of the library. I've just landed on this page looking for the same solution as @JSDevelopment17 Is it possible to have a dynamic Height for the whole swiper component without me calculating height of by view component?

**Comment by eyalabs** [comment] 2021-03-24 07:45
Hello again,
I've checked this out, setting `height: '100%'` works well! The problem is mainly with non-fixed `width`.
A workaround is to use `Dimensions.get('window').width` instead of `'100%'`.
Another fix I saw in our code, is by adding `style={{ alignItems: "stretch", flexGrow: 1 }}` to the `SwipeCards` components  and then you can use percent of the parent's size!

I've tested both solutions using the example code provided (so if it doesn't work for you, try the example code to figure what's the difference)

I'll work to refine the styling issues of the lib in later versions (#11 )! Thank for reminding me that it was a problem 😄 .

**Comment by eyalabs** [comment] 2021-03-24 07:45
I'll keep this open for other users

**Comment by creativemind1** [comment] 2021-03-24 08:59
My before and after elements seems to overlap with the Swiper Component, it doesn't have a fixed height, how do I give fixed dynamic height?
```
<View style={styles.mainContainer}>
                        {ifExists && (
                            <View style={styles.mainContainer}>
                                <Text bold style={styles.title}>
                                  My Title
                                </Text>
                                <Text style={styles.swipeRight}>My Description</Text>

                                <View style={{ flex: 1, position: 'relative' }}>
                                    <SwipeCards
                                        containerStyle={styles.container}
                                        dragY={false}
                                        allowGestureTermination={false}
                                        cards={myArray}
                                        renderCard={cardData => renderCard(cardData)}
                                        stack={true}
                                        stackDepth={myArray.length}
                                        stackOffsetX={4}
                                        stackOffsetY={-22}
                                        onClickHandler={() => null}
                                        showYup={false}
                                        showNope={false}
                                        smoothTransition={true}
                                    />
                                </View>
                            </View>
                        )}
                        <View>
                            <Text bold style={styles.title}>
                             My Test
                            </Text>
                        </View>
     </View>
```

**Comment by eyalabs** [comment] 2021-03-24 11:39
Sorry, I can't understand your question.
In stack mode, it is very problematic to use percent as a size. It is meant for fixed sizes only.
@JSDevelopment17 please update if this fixed your issue...

**Comment by creativemind1** [comment] 2021-03-24 11:42
How do I use Swipe component without overlapping  the next elements.
Because of position absolute, it is moving to the top overlapping all the
elements

**Comment by eyalabs** [comment] 2021-03-24 11:47
Don't use stack mode 😕 - remove `stack={true}`.
Sorry but this is not relevant to the issue at hand. Please read the documentation thoroughly.

**Comment by creativemind1** [comment] 2021-03-24 11:59
Is there any way to achieve this using `stack={true}`? I just need to get the dynamic height in the parent view

**Comment by eyalabs** [comment] 2021-03-24 12:09
Currently - NO.

**Comment by JSDevelopment17** [comment] 2021-03-29 21:41
Apologies for the delay.
I implemented an onLayout workaround which worked for me:
`onPageLayout = (event) => {
        const { width, height } = event.nativeEvent.layout;
        this.setState({
            cardWidth: width,
            cardHeight: height
        })
      }; `

**Comment by eyalabs** [comment] 2021-03-30 04:58
Yes it is another solution.

**Closed** 2021-07-12 04:55 UTC
Labels: good first issue, question
